#!/bin/bash
# java -Xmx1024M -Xmx1024M -jar minecraft_server*.jar nogui
# export LD_LIBRARY_PATH="/usr/lib/jvm/java-7-oracle/jre/lib/i386/"
# NOTE commented out the above line, as I'm using openjdk-8-jre
java -jar /opt/minecraft/minecraft_server*.jar
